export const SET_CURRENT_LEVEL_NUMBER = 'SET_CURRENT_LEVEL_NUMBER'
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_LOADED_STATUS = 'SET_LOADED_STATUS'
